//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diary
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Diary()
        {
            this.DiaryComment = new HashSet<DiaryComment>();
        }
    
        public int DiaryId { get; set; }
        public string Content { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public int UserId { get; set; }
        public bool IsPrivate { get; set; }
        public bool IsDel { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiaryComment> DiaryComment { get; set; }
    }
}
