//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiaryComment
    {
        public int CommentId { get; set; }
        public string CContent { get; set; }
        public int UserId { get; set; }
        public bool IsDel { get; set; }
        public int DiaryId { get; set; }
        public System.DateTime CreateTime { get; set; }
    
        public virtual Diary Diary { get; set; }
        public virtual User User { get; set; }
    }
}
